import Database.DB

insertPhase 1 "aaswd" "facil"
insertPhase 2 "wdsaw" "facil"
insertPhase 3 "swdaa" "facil"
insertPhase 4 "dwsdd" "facil"
insertPhase 5 "wswaa" "facil"
insertPhase 6 "dsaws" "facil"
insertPhase 7 "sswda" "facil"
insertPhase 8 "sdaws" "facil"
insertPhase 9 "ddasw" "facil"
insertPhase 10 "awsdw" "facil"
insertPhase 11 "sadws" "facil"
insertPhase 12 "dawsw" "facil"
insertPhase 13 "sawds" "facil"
insertPhase 14 "awdsa" "facil"
insertPhase 15 "wasda" "facil"

insertPhase 16 "wdsaawd" "medio"
insertPhase 17  "awdswsd" "medio" 
insertPhase 18 "wsadwsd" "medio"
insertPhase 19 "awsdwsd" "medio"
insertPhase 20 "awaaaws" "medio"
insertPhase 21 "dsadwsw" "medio"
insertPhase 22 "swdsadw" "medio"
insertPhase 23 "dswaswd" "medio"
insertPhase 24 "wsaswsw" "medio"
insertPhase 25 "awswwwd" "medio"
insertPhase 26 "dawdwsd" "medio"
insertPhase 27 "wsdawsw" "medio"
insertPhase 28 "awaawwd" "medio"
insertPhase 29 "ssadwsw" "medio"
insertPhase 30 "asdwswa" "medio"

insertPhase 31 "asswswsdsa" "dificil"  
insertPhase 32 "sdwasdwsas" "dificil"
insertPhase 33 "wswsswddsa" "dificil"
insertPhase 34 "daswswsdsa" "dificil"
insertPhase 35 "sdaswsawsd" "dificil"
insertPhase 36 "swddswssaw" "dificil"
insertPhase 37 "dwsawsawds" "dificil"
insertPhase 38 "sasdaswssw" "dificil"
insertPhase 39 "daddwsasws" "dificil"
insertPhase 40 "sawdswswsd" "dificil"
insertPhase 41 "wasdwsswds" "dificil"
insertPhase 42 "wswsdwswsw" "dificil"
insertPhase 43 "asddsaswas" "dificil"
insertPhase 44 "dsdsswasds" "dificil"
insertPhase 45 "sawsdwsasd" "dificil"

